apiVersion: v1
kind: Service
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels:
{{ include "eclipse-mosquitto.labels" . | indent 4 }}
   {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP:  {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.ports.mqtt.port }}
      targetPort: {{ .Values.container.ports.mqtt.name }}
      protocol: TCP
      name: {{ .Values.service.ports.mqtt.name }}
    - port: {{ .Values.service.ports.mqtts.port }}
      targetPort: {{ .Values.container.ports.mqtts.name }}
      protocol: TCP
      name: {{ .Values.service.ports.mqtts.name }}
  selector:
    app.kubernetes.io/name: {{ include "eclipse-mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
